import swaggerJsdoc from "swagger-jsdoc";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT) || 3001;
const BASE_URL = process.env.PUBLIC_URL || process.env.PUBLIC_SITE_URL || `http://localhost:${PORT}`;

const options = {
  definition: {
    openapi: "3.0.3",
    info: {
      title: "Iraniu Directory API",
      version: "1.0.0",
      description:
        "Public REST API for the Iraniu UK Business Directory. " +
        "Register, log in, browse businesses, add your own listing, and submit claims.",
      contact: { email: "admin@iraniu.uk" },
      license: { name: "Proprietary" },
    },
    servers: [{ url: `${BASE_URL}/api/v1`, description: "v1" }],
    components: {
      securitySchemes: {
        BearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description:
            "Pass the JWT returned by `/auth/login` or `/auth/register` as `Authorization: Bearer <token>`.",
        },
      },
      schemas: {
        Error: {
          type: "object",
          properties: {
            error: { type: "string" },
            hint: { type: "string" },
          },
        },
        UserProfile: {
          type: "object",
          properties: {
            id: { type: "integer" },
            name: { type: "string" },
            email: { type: "string", format: "email" },
            phone: { type: "string", nullable: true },
            created_at: { type: "string", format: "date-time" },
          },
        },
        Business: {
          type: "object",
          properties: {
            id: { type: "integer" },
            slug: { type: "string" },
            name_fa: { type: "string", description: "Business name (Persian/English)" },
            description: { type: "string", nullable: true },
            category: { type: "string", nullable: true },
            phone: { type: "string", nullable: true },
            mobile: { type: "string", nullable: true },
            address: { type: "string", nullable: true },
            postcode: { type: "string", nullable: true },
            city: { type: "string", nullable: true },
            price_range: { type: "string", nullable: true },
            cover_image_url: { type: "string", nullable: true },
            google_review_url: { type: "string", nullable: true },
            reservation_link: { type: "string", nullable: true },
            claimed: { type: "integer", description: "1 = claimed by a manager, 0 = unclaimed" },
            package: { type: "string", enum: ["basic", "premium", "featured"] },
            listing_approval: {
              type: "string",
              enum: ["approved", "pending", "rejected"],
            },
            rating: { type: "number", nullable: true },
            hours_json: { type: "string", nullable: true, description: "JSON string of opening hours" },
            subtitle: { type: "string", nullable: true },
            created_at: { type: "string", format: "date-time" },
          },
        },
        BusinessInput: {
          type: "object",
          required: ["name_fa"],
          properties: {
            name_fa: { type: "string", minLength: 2, maxLength: 200, description: "Business name" },
            description: { type: "string", maxLength: 5000 },
            category: { type: "string", maxLength: 100 },
            phone: { type: "string", maxLength: 30 },
            mobile: { type: "string", maxLength: 30 },
            address: { type: "string", maxLength: 500 },
            postcode: { type: "string", maxLength: 20 },
            city: { type: "string", maxLength: 100 },
            price_range: { type: "string", maxLength: 50 },
            google_review_url: { type: "string", format: "uri" },
            reservation_link: { type: "string", format: "uri" },
            hours_json: { type: "string", description: "JSON string of opening hours" },
            subtitle: { type: "string", maxLength: 300 },
            listing_contact_email: { type: "string", format: "email" },
          },
        },
        Category: {
          type: "object",
          properties: {
            id: { type: "integer" },
            name: { type: "string" },
            icon: { type: "string", nullable: true, description: "Emoji or icon identifier for the category" },
            sort_order: { type: "integer" },
          },
        },
        PaginatedBusinesses: {
          type: "object",
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/Business" } },
            total: { type: "integer" },
            page: { type: "integer" },
            limit: { type: "integer" },
            pages: { type: "integer" },
          },
        },
        TokenResponse: {
          type: "object",
          properties: {
            token: { type: "string", description: "JWT bearer token (7-day expiry)" },
            user: { $ref: "#/components/schemas/UserProfile" },
          },
        },
        ClaimInput: {
          type: "object",
          required: ["applicant_name", "email"],
          properties: {
            applicant_name: { type: "string" },
            email: { type: "string", format: "email" },
            phone: { type: "string" },
            message: { type: "string" },
          },
        },
        Service: {
          type: "object",
          properties: {
            id: { type: "integer" },
            slug: { type: "string" },
            name: { type: "string", description: "Service name" },
            description: { type: "string", nullable: true },
            service_type: { type: "string", nullable: true, description: "Category/type of service" },
            provider_name: { type: "string", nullable: true, description: "Name of the person or company providing the service" },
            phone: { type: "string", nullable: true },
            mobile: { type: "string", nullable: true },
            email: { type: "string", nullable: true },
            whatsapp: { type: "string", nullable: true },
            website: { type: "string", nullable: true },
            instagram: { type: "string", nullable: true },
            city: { type: "string", nullable: true },
            area_coverage: { type: "string", nullable: true, description: "Areas/cities covered (e.g. 'London, Manchester')" },
            postcode: { type: "string", nullable: true },
            pricing_info: { type: "string", nullable: true, description: "Free-text pricing description" },
            pricing_from: { type: "string", nullable: true, description: "Starting price amount" },
            pricing_currency: { type: "string", default: "GBP" },
            languages: { type: "string", nullable: true, description: "Languages offered (e.g. 'Persian, English')" },
            availability: { type: "string", nullable: true, description: "Availability info (e.g. 'Mon-Fri 9am-6pm')" },
            cover_image_url: { type: "string", nullable: true },
            status: { type: "string", enum: ["pending", "approved", "rejected"] },
            created_at: { type: "string", format: "date-time" },
          },
        },
        ServiceInput: {
          type: "object",
          required: ["name", "service_type"],
          properties: {
            name: { type: "string", minLength: 2, maxLength: 200, description: "Service name" },
            description: { type: "string", maxLength: 5000 },
            service_type: {
              type: "string",
              maxLength: 100,
              description: "Category of service",
              example: "legal-immigration",
              enum: [
                "legal-immigration", "financial-accounting", "it-technology",
                "translation", "education-tutoring", "health-medical",
                "beauty-wellness", "home-maintenance", "business-consulting",
                "photography-media", "marketing-advertising", "real-estate",
                "mental-health", "automotive", "other"
              ],
            },
            provider_name: { type: "string", maxLength: 200 },
            phone: { type: "string", maxLength: 30 },
            mobile: { type: "string", maxLength: 30 },
            email: { type: "string", format: "email" },
            whatsapp: { type: "string", maxLength: 30 },
            website: { type: "string", format: "uri" },
            instagram: { type: "string", maxLength: 100 },
            city: { type: "string", maxLength: 100 },
            area_coverage: { type: "string", maxLength: 300 },
            postcode: { type: "string", maxLength: 20 },
            pricing_info: { type: "string", maxLength: 500 },
            pricing_from: { type: "string", maxLength: 20 },
            pricing_currency: { type: "string", default: "GBP", maxLength: 10 },
            languages: { type: "string", maxLength: 200, example: "Persian, English" },
            availability: { type: "string", maxLength: 300, example: "Mon-Fri 9am-6pm" },
            cover_image_url: { type: "string", format: "uri" },
          },
        },
        PaginatedServices: {
          type: "object",
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/Service" } },
            total: { type: "integer" },
            page: { type: "integer" },
            limit: { type: "integer" },
            pages: { type: "integer" },
          },
        },
        Reservation: {
          type: "object",
          properties: {
            id: { type: "integer" },
            business_slug: { type: "string" },
            customer_name: { type: "string" },
            customer_email: { type: "string", format: "email" },
            customer_phone: { type: "string", nullable: true },
            reservation_date: { type: "string", format: "date", description: "YYYY-MM-DD" },
            reservation_time: { type: "string", description: "HH:MM (24h)" },
            party_size: { type: "integer", minimum: 1, maximum: 50 },
            occasion: {
              type: "string", nullable: true,
              enum: ["birthday", "anniversary", "date", "business", "family", "celebration", "other", null],
            },
            seating_preference: {
              type: "string", nullable: true,
              enum: ["indoor", "outdoor", "booth", "window", "bar", "private", "no-preference", null],
            },
            special_requests: { type: "string", nullable: true, description: "Dietary or accessibility needs" },
            notes: { type: "string", nullable: true },
            status: {
              type: "string",
              enum: ["pending", "confirmed", "seated", "completed", "cancelled", "no-show"],
            },
            confirmation_code: { type: "string", description: "8-character code for self-service cancellation" },
            source: { type: "string", enum: ["website", "api"] },
            cancelled_at: { type: "string", nullable: true },
            cancellation_reason: { type: "string", nullable: true },
            confirmed_at: { type: "string", nullable: true },
            created_at: { type: "string", format: "date-time" },
          },
        },
        ReservationInput: {
          type: "object",
          required: ["business_slug", "customer_name", "customer_email", "reservation_date", "reservation_time", "party_size"],
          properties: {
            business_slug: { type: "string", description: "Slug of the restaurant/business" },
            customer_name: { type: "string", description: "Full name of the guest" },
            customer_email: { type: "string", format: "email" },
            customer_phone: { type: "string", maxLength: 30 },
            reservation_date: { type: "string", format: "date", description: "Date of reservation (YYYY-MM-DD)" },
            reservation_time: { type: "string", description: "Time in 24h format (HH:MM)", example: "19:30" },
            party_size: { type: "integer", minimum: 1, maximum: 50, description: "Number of guests" },
            occasion: {
              type: "string", nullable: true,
              enum: ["birthday", "anniversary", "date", "business", "family", "celebration", "other"],
              description: "Special occasion type",
            },
            seating_preference: {
              type: "string", nullable: true,
              enum: ["indoor", "outdoor", "booth", "window", "bar", "private", "no-preference"],
              default: "no-preference",
            },
            special_requests: { type: "string", maxLength: 1000, description: "Dietary restrictions, allergies, accessibility needs" },
            notes: { type: "string", maxLength: 500 },
          },
        },
        Ad: {
          type: "object",
          properties: {
            id: { type: "integer" },
            slug: { type: "string" },
            title: { type: "string" },
            description: { type: "string", nullable: true },
            image_url: { type: "string", nullable: true },
            target_url: { type: "string", nullable: true },
            ad_type: { type: "string", enum: ["listing", "banner", "spotlight"] },
            placement: { type: "string", enum: ["listings", "home", "sidebar"] },
            business_slug: { type: "string", nullable: true },
            contact_name: { type: "string", nullable: true },
            contact_email: { type: "string", format: "email" },
            contact_phone: { type: "string", nullable: true },
            budget_gbp: { type: "number", nullable: true },
            start_date: { type: "string", format: "date", nullable: true },
            end_date: { type: "string", format: "date", nullable: true },
            status: { type: "string", enum: ["pending", "active", "paused", "expired", "rejected"] },
            impression_count: { type: "integer" },
            click_count: { type: "integer" },
            notes: { type: "string", nullable: true },
            created_at: { type: "string", format: "date-time" },
          },
        },
        AdInput: {
          type: "object",
          required: ["title", "contact_email"],
          properties: {
            title: { type: "string", minLength: 2, maxLength: 200, description: "Ad headline / title" },
            description: { type: "string", maxLength: 2000 },
            image_url: { type: "string", format: "uri", description: "Banner image URL" },
            target_url: { type: "string", format: "uri", description: "URL visitors go to when clicking the ad" },
            ad_type: {
              type: "string",
              enum: ["listing", "banner", "spotlight"],
              description: "listing = sponsored directory entry, banner = image banner, spotlight = homepage feature",
            },
            placement: {
              type: "string",
              enum: ["listings", "home", "sidebar"],
              description: "Where the ad is shown",
            },
            business_slug: { type: "string", description: "Optionally link to an existing business slug" },
            contact_name: { type: "string", maxLength: 200 },
            contact_email: { type: "string", format: "email", description: "Your contact email" },
            contact_phone: { type: "string", maxLength: 30 },
            budget_gbp: { type: "number", description: "Monthly budget in GBP" },
            start_date: { type: "string", format: "date" },
            end_date: { type: "string", format: "date" },
            notes: { type: "string", maxLength: 1000 },
          },
        },
        HomeSection: {
          type: "object",
          description: "A content block displayed on the home page, controlled by admins.",
          properties: {
            id: { type: "integer" },
            title: { type: "string", description: "Section heading shown to users" },
            subtitle: { type: "string", nullable: true, description: "Optional sub-heading" },
            eyebrow: { type: "string", nullable: true, description: "Small label above the title" },
            section_type: {
              type: "string",
              enum: ["category-grid", "featured-listings", "services-grid", "city-grid"],
              description: "Determines what content is rendered in this block",
            },
            category_filter: {
              type: "string", nullable: true,
              description: "Comma-separated category names to show (category-grid only). Empty = all.",
            },
            icon: { type: "string", nullable: true, description: "Emoji or icon shown beside the title" },
            background: {
              type: "string",
              enum: ["white", "gray", "dark"],
              description: "Background style for this section",
            },
            max_items: { type: "integer", description: "Maximum number of items to display" },
            sort_order: { type: "integer", description: "Display order (ascending)" },
          },
        },
        PaginatedAds: {
          type: "object",
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/Ad" } },
            total: { type: "integer" },
            page: { type: "integer" },
            limit: { type: "integer" },
            pages: { type: "integer" },
          },
        },
      },
    },
    tags: [
      { name: "Auth", description: "Register, login, and manage your account" },
      { name: "Businesses", description: "Browse and manage business listings" },
      { name: "Services", description: "Browse and manage professional service listings" },
      { name: "Reservations", description: "Book a table at a restaurant or venue" },
      { name: "Categories", description: "Business categories" },
      { name: "Claims", description: "Claim an unclaimed business listing" },
      { name: "Ads", description: "Create and manage promotional ads for your business" },
      { name: "Sections", description: "Home page section layout — admin-controlled content blocks" },
    ],
  },
  apis: [path.join(__dirname, "v1", "*.js")],
};

export const swaggerSpec = swaggerJsdoc(options);
